services:
    app:
        build: .
        restart: unless-stopped
        environment:
            NODE_ENV: production
        networks:
            - traefik-proxy
        labels:
            traefik.enable: "true"

            traefik.http.routers.montecarlo-tls.rule: Host(`${DOMAIN}`)
            traefik.http.routers.montecarlo-tls.entrypoints: websecure
            traefik.http.routers.montecarlo-tls.tls: "true"
            traefik.http.routers.montecarlo-tls.tls.certresolver: defaultresolver
            traefik.http.routers.montecarlo-tls.service: montecarlo

            # Service
            traefik.http.services.montecarlo.loadbalancer.server.port: "3000"

            # WebSocket sticky sessions (required for socket.io)
            traefik.http.services.montecarlo.loadbalancer.sticky.cookie: "true"
            traefik.http.services.montecarlo.loadbalancer.sticky.cookie.name: montecarlo_session

networks:
    traefik-proxy:
        external: true
